### ISSUE TITLE
ajax chat

### ISSUE THREAD

**Issue by dxeglow** [veerko/secure-gamesense-forum#6]
Hello! I dont understand what i need to do for make fully working chat! Can you give me a tutorial ( i installed db tables from 'install.php')

i finished it only to this
![chrome_GjE8EE6CZm](https://github.com/st1koo/secure-gamesense-forum/assets/88434607/83325ec8-c1dc-47b6-ba1e-7bb193bbbd15)
im using version for FluxBB
Php version: 5.6

**Comment by veerko** [comment]
seems like you haven't included the chatbox in the common.php file and index.
